server:
  port: 8908
  main:
    allow-bean-definition-overriding: true  # 本条配置只能放在本地配置，放置远程配置无效
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"